import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [account,setAccount] = useState("");
  function getValue(){
    const name = document.getElementById("list").value;
    return name;
  }

  const connect = async()=>{
    try{
      const name = getValue()
      if(name == "eth"){
        await window.ethereum.enable();
        const accounts = await window.ethereum.request({ method: 'eth_accounts' });
        setAccount(accounts[0]);
      }
      else if(name=="sol"){
        await window.solana.connect();
        const accounts = await window.solana.request({ method: 'connect' });
        setAccount(accounts.publicKey.toString());
      }
      else if(name="ada"){
        console.log(window.cardano)
        await window.cardano.enable();
        const accounts = await window.cardano.getUsedAddresses()
        setAccount(accounts[0]);
      }
      else{

      }
    }
    catch(e){
      alert(e);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="../path/to/flowbite/dist/flowbite.js"></script>
        <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.7/dist/flowbite.min.css" />
        <script src="https://unpkg.com/flowbite@1.4.7/dist/flowbite.js"></script>
      </Head>
      <div>
        <div className = "flex flex-row-reverse items-center p-5">
          <button className='p-6 rounded-xl bg-blue-200' onClick={connect}>Connect Wallet</button>
          <select className='px-10 mr-10' id='list' onChange={getValue}>
            <option value="eth">Ethereum</option>
            <option value="sol">Solano</option>
            <option value="ada">Cardano</option>
            {/* <option value="waves">Waves</option> */}
          </select>
        </div>
        <div>
          {
            account=="" ?
            <h1>Connect Wallet</h1>
            :
            <h1>{getValue()} address is {account}</h1>

          }
        </div>
      </div>
    </div>
  )
}
